# ===============================
# APPLICATION
# ===============================
spring.application.name=khathabook-backend
server.port=${PORT:8084}

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=${MYSQL_URL:${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/khathabook?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}}
spring.datasource.username=${MYSQLUSER:${DB_USER:root}}
spring.datasource.password=${MYSQLPASSWORD:${DB_PASSWORD:}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true	
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# EMAIL (OTP + INVOICE)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khathabook.noreply@gmail.com

# ⚠️ MOVE THIS TO ENV VARIABLE IN REAL PROJECT
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

google.client.id=${GOOGLE_CLIENT_ID:}
google.client.secret=${GOOGLE_CLIENT_SECRET:}
google.redirect.uri=${GOOGLE_REDIRECT_URL:http://localhost:8084/auth/google/callback}
# ===============================
# MULTIPART (large images)
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
