package com.khathabook.model;

public enum ProductCategory {

    FRUITS_VEGETABLES,
    STAPLES_GRAINS,
    SPICES_MASALAS,
    COOKING_OILS_GHEE,
    DAIRY_PRODUCTS,
    BAKERY_BREAD,
    SNACKS_PACKAGED,
    READY_TO_EAT,
    MEAT_FISH_EGGS,
    BEVERAGES,
    PERSONAL_CARE,
    HOUSEHOLD_CLEANING,
    BABY_CARE,
    HEALTH_WELLNESS,
    PET_CARE,
    PAPER_DISPOSABLES,
    SEASONAL_FESTIVAL,
    MISCELLANEOUS
}
